[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
	lemmingdev/esp32-ble-gamepad@0.7.4
	makuna/NeoPixelBus@^2.8.4
	adafruit/Adafruit NeoPixel@^1.15.1
monitor_speed = 115200
upload_speed = 921000
build_flags =
   -DARDUINO_USB_MODE=1
   -DARDUINO_USB_CDC_ON_BOOT=0
   -DGBP_DEVICE_TYPE="esp32s-18650"
   -DGBP_DEVICE_TYPE_ESP32S_18650=1

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
lib_deps =
	lemmingdev/esp32-ble-gamepad@0.7.4
	makuna/NeoPixelBus@^2.8.4
	adafruit/Adafruit NeoPixel@^1.15.1
monitor_speed = 115200
upload_speed = 921000
build_flags =
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=0
    -DGBP_DEVICE_TYPE_ESP32_S3_DEVKITM_1=1